global:
  scrape_interval: 15s

scrape_configs:
  - job_name: api
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8080"]

  - job_name: scheduler
    metrics_path: /metrics
    static_configs:
      - targets: ["scheduler:9091"]

  - job_name: notifier
    metrics_path: /metrics
    static_configs:
      - targets: ["notifier:9092"]
